### PR TITLE
Add 'user-select' to vendor mixins

### PR DESCRIPTION
**Pull request by mehcode**
http://caniuse.com/#feat=user-select-none

----

This should probably generate as follows:

```
.unselectable {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

I'm not sure how you'd like adjust the vendor stuff to do the above.

### CODE REVIEW

**Comment by leny** [comment]
Hi, thanks for the report (and the request).

Will you please add some unit tests for this feature ?

**Comment by mehcode** [comment]
> Will you please add some unit tests for this feature ?

Added. Also updated to generate what I mentioned in the opening.

**Comment by leny** [comment]
Hi, thanks for the tests. I would prefer to keep using the ks-vendors() internal mixins, since the used vendors prefixes in the output will be dependent of which support you define with kouto swiss.
I will correct that with the merge.

**Comment by leny** [comment]
Has been implemented & published in version `0.11.7`.

Thanks again.

**Comment by mehcode** [comment]
@leny If you use your `ks-vendors` mixin it doesn't generate it 100% correctly (in my opinion).

It'd be missing the `-webkit-touch-callout: value` line.

**Comment by leny** [comment]
I'm a bit confused about including it, since it's really specific and not totally related to the `user-select` property.

In the current case, I think the best is to define your own mixin extending the one from kouto-swiss, like this : 

```
user-select( value )
        -webkit-touch-callout: value
        ks-vendor( "user-select", arguments, feature: "user-select-none" )
```

**Pull request merged**
